//LOCALHOST GET ALL CONTACTS
GET http://localhost:3000/contacts
###

// LOCALHOST GET ONE CONTACT
Get http://localhost:3000/contacts/65aecdc27b20443435a233e6
###

// LOCALHOST CREATE CONTACT
POST http://localhost:3000/contacts HTTP/1.1
Content-Type: application/json

{
    "firstName":"Darlyn",
    "lastName":"Kirby",
    "email":"darlyn@email.com",
    "favoriteColor":"yellow",
    "birthday":"08/19/1999"
}
###

// LOCALHOST UPDATE CONTACT
PUT http://localhost:3000/contacts/65aece607b20443435a233e7 HTTP/1.1
Content-Type: application/json

{
    "firstName":"Darlyn",
    "lastName":"Kirby",
    "email":"darlyn@email.com",
    "favoriteColor":"green",
    "birthday":"08/19/1999"
}
###

// LOCALHOST DELETE CONTACT
DELETE http://localhost:3000/contacts/65b55fef2a8b03809b24ba7e HTTP/1.1
###



// RENDER GET ALL CONTACTS
GET https://cse341-1sp5.onrender.com/contacts
###

// RENDER GET ONE CONTACT
GET https://cse341-1sp5.onrender.com/contacts/65aecdc27b20443435a233e6
###

// RENDER CREATE CONTACT
POST https://cse341-1sp5.onrender.com/contacts HTTP/1.1
Content-Type: application/json

{
    "firstName":"Darlyn",
    "lastName":"Kirby",
    "email":"darlyn@email.com",
    "favoriteColor":"yellow",
    "birthday":"08/19/1999"
}
###

// RENDER UPDATE CONTACT
PUT https://cse341-1sp5.onrender.com/contacts/65b563c2080988acd7a19616 HTTP/1.1
Content-Type: application/json

{
    "firstName":"Darlyn",
    "lastName":"Kirby",
    "email":"darlyn@email.com",
    "favoriteColor":"green",
    "birthday":"08/19/1999"
}
###

// RENDER DELETE CONTACT
DELETE https://cse341-1sp5.onrender.com/contacts/65b563c2080988acd7a19616 HTTP/1.1